### ISSUE TITLE
Chained source() calls overwrite previous sources instead of adding them

### ISSUE THREAD

**Issue by Michael1993** [verhas/javageci#10]
**Describe the bug**
When calling the following method in javax0.geci.engine.Geci, it overwrites previous calls because it uses the same key.
```java
public Geci source(String... directory) {
        directories.put(set(""), directory);
        return this;
    }
```

**To Reproduce**
Chain multiple .source calls after each other without specifying a Source.Set as the first parameter.

**Expected behavior**
Instead of overwriting the previous sources, the class should use an ID, that identifes different source calls?

**Comment by verhas** [comment]
The constructor of `Set` was modified so that when a set is created without a name (an empty string is a name) then it creates an artificial name.

```
        private Set(String name) {
            if (name == null) {
                name = randomUniqueName();
            }
            this.name = name;
        }

        private String randomUniqueName() {
            return "" + super.hashCode();
        }
```

**Comment by verhas** [comment]
There is also a new method `set()` (no argument) that calls `set(null)`. This should be used instead of `set("")`. Calling `set("")` has the same effect as `set(any string)` and such empty string is not a special value.

If the caller tries to define a set with a name that was already used it will throw an exception.
