### ISSUE TITLE
Question: Different than Lombok?

### ISSUE THREAD

**Issue by melloware** [verhas/javageci#22]
Hey sorry to post here but I saw your post on the Apache mailing list about Commons Lang and boilerplate code.

From looking at your documentation how is your code different than Project Lombok?? https://projectlombok.org/

I was looking through your docs and didn't see anything that was different or newer than Lombok. Just curious.

**Comment by verhas** [comment]
This is a common question. You can find the answer in the FAQ 

`https://github.com/verhas/javageci/blob/master/FAQ.md`

as this:

## How about Lombok?

Lombok is a special annotation processor that modifies the abstract
syntax tree (AST) during its execution. There are multiple issues with
such behavior that the project using it should live with. Before
deciding lombok you have to decide if you can and if you want to
live with these:

* The way Lombok works altering the AST it also modifies the Java
    language syntax. In some sense when you code using Lombok you are
    programing in a Java language with a Lombok flavor. This may also be
    a concern when you want to hire a developer to maintain the code:
    they have to know the lombok flavour. It may not be a big deal or it
    may be.
* The possibility to modify the AST is not part of the guaranteed API
    for the annotation processing tools. It means that Lombok may not
    work with some implementation of the Java compiler including future
    versions.
* There is no real source code generated by Lombok. The modified AST is
    fed into the compiler. That way debugging may be a bit harder when
    you want to put a breakpoint into somewhere the generated code. You
    can argue that this is not an issue, because you should not be
    debugging generated code. However, where would you put the
    breakpoint when you want to stop every time a setter is invoked? It
    is the body of the setter even you do not want to debug the setter
    itself. (See a few words about delombok later.) Some of the IDEs,
    like Eclipse or IntelliJ let you put a breakpoint on a method
    specifying the class and the name of the method. It is a bit more
    cumbersome than just clicking on the gutter on a specific line.
* Because there is no generated source code Lombok has to be part of the
    whole build process. It has to be available on the developer machine
    as well as on the CI server. It is hardly ever a problem but in some
    corporate environment the policy may not allow Lombok to be used on
    the CI server but the same time there is larger freedom on the
    developers machine.
* You can get rid of lombok. There is a project delombok that generates
    the source code for the functionality. This functionality is
    designed to get rid of lombok from a project and not to live with it
    continuously. After the code changed it is not trivial to get rid of
    the already generated and not needed code and to insert the new
    code.
* Lombok was not designed to be a framework for code generators. You
    have the generators that are available and that it mainly it. It is
    not impossible to write new generators into the Lombok project but
    it is not trivial and, mainly, it was not designed for that purpose.
    Java::Geci, on the other hand, is mainly a library/framework that
    provides API to write your own generators and the generators
    implemented in the `core` module are there as examples. Yes, we know
    that most of the developers will only use these generators, but we
    also have the hope that other developers will create generators of
    their own. There are already examples in some source code
    proprietary projects.
